package com.interview.notes.code.year.y2026.march.common.tes1;

import java.util.LinkedHashMap;
import java.util.function.Function;
import java.util.stream.Collectors;

public class NonRepeatedChars { // Defines the main class that contains our logic and testing methods

    public static String getUnique(String text) { // Method to process the string and return non-repeated characters
        if (text == null || text.isEmpty()) return ""; // Guard clause: returns empty string immediately if input is null or empty

        return text.chars() // Converts the input String into an IntStream representing character ASCII codes
            .mapToObj(c -> (char) c) // Converts each primitive int code back into a Character object
            .collect(Collectors.groupingBy(Function.identity(), LinkedHashMap::new, Collectors.counting())) // Groups characters by themselves, keeping order with LinkedHashMap, and counts them
            .entrySet().stream() // Converts the map's key-value pairs back into a fresh Stream
            .filter(entry -> entry.getValue() == 1) // Filters the stream to keep ONLY entries where the character count is exactly 1
            .map(entry -> String.valueOf(entry.getKey())) // Extracts the Character key from the map entry and turns it into a String
            .collect(Collectors.joining()); // Glues all the single-character strings together into one final result String
    }

    public static void main(String[] args) { // Main method used as our entry point to run test cases
        
        System.out.println("Running Tests..."); // Prints a starting message to the console
        
        runTest("TEST", "ES", "Basic provided case"); // Tests the exact input/output provided in your image
        
        runTest("JAVA", "JV", "Multiple uniques case"); // Tests a standard word with mixed repeating and non-repeating characters
        
        runTest("AABBCC", "", "No uniques case"); // Tests a string where every character repeats, expecting empty output
        
        runTest("", "", "Empty string case"); // Tests an edge case with an empty string to ensure no crashes occur
        
        var largeInput = "A".repeat(100000) + "B" + "C".repeat(100000); // Uses Java 11+ String.repeat to generate a massive string efficiently
        runTest(largeInput, "B", "Large data input case"); // Tests the massive string to ensure the O(N) complexity handles large data fast
    }

    private static void runTest(String input, String expected, String testName) { // Helper method to evaluate tests and print PASS/FAIL
        var actual = getUnique(input); // Uses Java 10+ 'var' for cleaner code, calling our logic method with the input
        var isPass = expected.equals(actual); // Compares the expected string with the actual string generated by our method
        var resultText = isPass ? "PASS" : "FAIL"; // Uses a ternary operator to set the result text to PASS or FAIL
        System.out.println(resultText + " | " + testName + " | Input: " + format(input) + " | Output: " + actual); // Prints the beautifully formatted test result to the console
    }

    private static String format(String str) { // Helper method to format long strings for console output so they don't flood the screen
        return str.length() > 20 ? str.substring(0, 10) + "...(truncated)" : str; // If string is too long, cuts it off and adds 'truncated' text, otherwise returns it
    }
}